//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landscape.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsage
    {
        public int IDEquipmentUsage { get; set; }
        public Nullable<int> IDEquipment { get; set; }
        public Nullable<int> IDWorker { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
