//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landscape.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int IDInvoice { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IDInvoiceStatus { get; set; }
        public System.DateTime IssueDate { get; set; }
    
        public virtual InvoiceStatuses InvoiceStatuses { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
