//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landscape.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plants()
        {
            this.OrdersPlantsMaterials = new HashSet<OrdersPlantsMaterials>();
        }
    
        public int IDPlant { get; set; }
        public Nullable<int> IDPlantType { get; set; }
        public string Name { get; set; }
        public string GrowthConditions { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersPlantsMaterials> OrdersPlantsMaterials { get; set; }
        public virtual PlantTypes PlantTypes { get; set; }
    }
}
