//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landscape.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int IDReview { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<short> Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
